### ISSUE TITLE
The TODO list

### ISSUE THREAD

**Issue by sdudnic** [sdudnic/covid-19#5]
- [ ] migrate to [VueJS](https://vuejs.org/v2/guide) the index page;
 - [ ] finish migrate the interface to [Vuetify](https://vuetifyjs.com/en/);
 - [ ] make the combobox searcheable and editable, using the Vuetify [`v-autocomplete`](https://vuetifyjs.com/en/components/autocompletes/)
